// generated by ai not by me fr im honest
import { useState, useEffect, useCallback, useRef } from 'react';

// Ocean & Hacker inspired matrix glyphs
const GLYPHS = '░▒▓█║╬═╝╚╗╔╩╦╠═█▀▄■+-*/<>[]{}_^!';

export default function HackerShuffle({
    text = "unclePRO",
    duration = 0.4,       // Overall decoding duration in seconds
    fps = 30,             // Refresh rate of the shuffle animation
    triggerOnHover = true,
    className = ""
}) {
    const [displayText, setDisplayText] = useState(text);
    const isAnimating = useRef(false);
    const timeoutIds = useRef([]);

    const startShuffle = useCallback(() => {
        if (isAnimating.current) return;
        isAnimating.current = true;

        // Clear any lingering animation timeouts
        timeoutIds.current.forEach(clearTimeout);
        timeoutIds.current = [];

        const totalFrames = Math.floor(duration * fps);
        const frameInterval = 1000 / fps;

        text.split('').forEach((char, charIndex) => {
            // Space characters shouldn't scramble; keep them clean
            if (char === ' ') return;

            // Calculate when this specific letter should stop scrambling
            const revealFrame = Math.floor((charIndex / text.length) * totalFrames * 0.6) + Math.floor(Math.random() * (totalFrames * 0.4));

            for (let frame = 0; frame <= totalFrames; frame++) {
                const timeoutId = setTimeout(() => {
                    setDisplayText((prev) => {
                        const nextArray = prev.split('');
                        
                        if (frame >= revealFrame) {
                            nextArray[charIndex] = text[charIndex]; // Lock in final character
                        } else {
                            nextArray[charIndex] = GLYPHS[Math.floor(Math.random() * GLYPHS.length)]; // Shuffle glyph
                        }
                        return nextArray.join('');
                    });

                    // Unlock the animation status on the final frame of the final character
                    if (charIndex === text.length - 1 && frame === totalFrames) {
                        isAnimating.current = false;
                    }
                }, frame * frameInterval);

                timeoutIds.current.push(timeoutId);
            }
        });
    }, [text, duration, fps]);

    // Initial trigger on component mount
    useEffect(() => {
        startShuffle();
        return () => timeoutIds.current.forEach(clearTimeout);
    }, [startShuffle]);

    return (
        <p
            onMouseEnter={triggerOnHover ? startShuffle : undefined}
            className={`font-mono uppercase tracking-wider select-none text-[4rem] leading-none text-cyan-400 drop-shadow-[0_0_10px_rgba(34,211,238,0.6)] cursor-default ${className}`}
        >
            {displayText}
        </p>
    );
}