// generated by ai not by me fr im honest
import { useEffect, useState } from 'react';
import { ActivityCalendar } from 'react-activity-calendar';

export default function LeetCodeCalendar({ username }) {
    const [data, setData] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        // Fetch data from a highly available public LeetCode API wrapper
        fetch(`https://alfa-leetcode-api.onrender.com/${username}/calendar`)
            .then(res => res.json())
            .then(apiData => {
                const submissions = JSON.parse(apiData.submissionCalendar);
                
                // 1. Generate an empty array of the last 365 days
                const calendarData = [];
                const today = new Date();
                for (let i = 365; i >= 0; i--) {
                    const d = new Date(today);
                    d.setDate(d.getDate() - i);
                    calendarData.push({ 
                        date: d.toISOString().split('T')[0], 
                        count: 0, 
                        level: 0 
                    });
                }

                // 2. Populate the array with actual LeetCode submissions
                Object.keys(submissions).forEach(timestamp => {
                    const d = new Date(timestamp * 1000);
                    const dateStr = d.toISOString().split('T')[0];
                    
                    const dayObj = calendarData.find(item => item.date === dateStr);
                    if (dayObj) {
                        const count = submissions[timestamp];
                        dayObj.count = count;
                        
                        // Assign color intensity levels based on problem count
                        if (count > 0) dayObj.level = 1;
                        if (count > 2) dayObj.level = 2;
                        if (count > 4) dayObj.level = 3;
                        if (count > 6) dayObj.level = 4;
                    }
                });
                
                setData(calendarData);
                setLoading(false);
            })
            .catch(err => {
                console.error("Failed to fetch LeetCode data", err);
                setLoading(false);
            });
    }, [username]);

    if (loading) return <p className="text-cyan-400 animate-pulse">Decrypting LeetCode Data...</p>;
    if (data.length === 0) return <p className="text-red-400">Connection Terminated: No Data</p>;

    return (
        <ActivityCalendar 
            data={data} 
            colorScheme="dark"
            theme={{
                // Matches the cyan gradient from your GitHub graph perfectly
                dark: ['#14191f', '#0891b2', '#06b6d4', '#22d3ee', '#67e8f9']
            }}
            labels={{
                totalCount: '{{count}} problems solved in the past year',
            }}
            className="text-white/90 !overflow-visible"
        />
    );
}